# Generated by Django 4.2.1 on 2023-06-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcategory",
            name="cover",
            field=models.ImageField(blank=True, upload_to="rooms"),
        ),
    ]
