# Generated by Django 4.2.1 on 2023-06-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_roomcategory_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="cover",
            field=models.FileField(blank=True, upload_to="rooms"),
        ),
        migrations.AlterField(
            model_name="roomcategory",
            name="cover",
            field=models.FileField(blank=True, upload_to="rooms"),
        ),
        migrations.AlterField(
            model_name="roomcategory",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
