# Generated by Django 4.2.1 on 2023-06-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_addon_cover_alter_roomcategory_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="management.customer",
            ),
        ),
    ]
