# Generated by Django 4.2.1 on 2023-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_reservation_code_alter_reservation_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
