# Generated by Django 4.2.1 on 2023-07-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_reservation_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
