@url = http://localhost:8000/api
###
get {{url}}/reservations/1/

HTTP/1.1 200  - OK
date: Wed, 28 Jun 2023 21:35:01 GMT
server: WSGIServer/0.2 CPython/3.11.3
content-type: application/json
vary: Accept, Cookie
allow: GET, HEAD, OPTIONS
x-frame-options: DENY
content-length: 723
x-content-type-options: nosniff
referrer-policy: same-origin
cross-origin-opener-policy: same-origin
###
post {{url}}/reservations/make_reservation/
Content-Type: application/json

{
    "first_name":"Innocent",
    "last_name":"Moses",
    "phone_number":"09163674665",
    "email_address":"skykisco8@gmail.com",
    "identification_type":"national_id",
    "identification_number":"22339489885",
    "arrival_date":"2023-07-10",
    "arrival_time":"12:00:00",
    "departure_date":"2023-07-13 ",
    "departure_time":"16:00",
    "guest_count":1,
    "room":3
}

HTTP/1.1 200  - OK
date: Wed, 05 Jul 2023 07:02:36 GMT
server: WSGIServer/0.2 CPython/3.11.3
content-type: application/json
vary: Accept, Origin, Cookie
allow: POST, OPTIONS
x-frame-options: DENY
content-length: 686
x-content-type-options: nosniff
referrer-policy: same-origin
cross-origin-opener-policy: same-origin
###
http://localhost:8000/api/categories/

HTTP/1.1 200  - OK
date: Fri, 30 Jun 2023 07:19:28 GMT
server: WSGIServer/0.2 CPython/3.11.3
content-type: application/json
vary: Accept, Origin, Cookie
allow: GET, HEAD, OPTIONS
x-frame-options: DENY
content-length: 522
x-content-type-options: nosniff
referrer-policy: same-origin
cross-origin-opener-policy: same-origin
###
GET http://localhost:8000/api/reservations/25/

HTTP/1.1 404  - Not Found
date: Mon, 17 Jul 2023 21:46:04 GMT
server: WSGIServer/0.2 CPython/3.11.3
content-type: application/json
vary: Accept, Origin, Cookie
allow: GET, HEAD, OPTIONS
x-frame-options: DENY
content-length: 60
x-content-type-options: nosniff
referrer-policy: same-origin
cross-origin-opener-policy: same-origin